export interface EAPhase {
  id: string;
  name: string;
  description: string;
  activities: Activity[];
  deliverables: Deliverable[];
  automationCapabilities: AutomationCapability[];
  emailTemplates: EmailTemplate[];
  surveys: Survey[];
}

export interface Activity {
  id: string;
  name: string;
  description: string;
  automationType: 'manual' | 'semi-automated' | 'fully-automated';
  owner: string;
  duration: string;
  tools?: string[];
}

export interface Deliverable {
  id: string;
  name: string;
  type: 'document' | 'presentation' | 'report' | 'dashboard';
  template?: string;
  autoGenerated: boolean;
}

export interface AutomationCapability {
  id: string;
  name: string;
  type: 'email' | 'survey' | 'analysis' | 'report' | 'workflow';
  status: 'available' | 'in-development' | 'planned';
  description: string;
}

export interface EmailTemplate {
  id: string;
  name: string;
  subject: string;
  body: string;
  recipients: string[];
  attachments?: string[];
  schedule?: string;
  variables: string[];
}

export interface Survey {
  id: string;
  name: string;
  purpose: string;
  targetAudience: string[];
  questions: SurveyQuestion[];
  automationLevel: 'manual' | 'automated';
}

export interface SurveyQuestion {
  id: string;
  question: string;
  type: 'text' | 'radio' | 'checkbox' | 'scale' | 'matrix';
  required: boolean;
  options?: string[];
  category: string;
}

// EA Review Phases
export const eaReviewPhases: EAPhase[] = [
  {
    id: 'initiate',
    name: 'INITIATE',
    description: 'Kickoff and stakeholder alignment phase',
    activities: [
      {
        id: 'stakeholder-analysis',
        name: 'Perform stakeholder analysis',
        description: 'Identify and analyze key stakeholders',
        automationType: 'semi-automated',
        owner: 'EA Team Lead',
        duration: '2 days',
        tools: ['Stakeholder Matrix Tool', 'RACI Generator']
      },
      {
        id: 'schedule-meetings',
        name: 'Schedule meetings and workshops',
        description: 'Coordinate and schedule stakeholder sessions',
        automationType: 'fully-automated',
        owner: 'EA Coordinator',
        duration: '1 day',
        tools: ['Calendar Integration', 'Meeting Scheduler Bot']
      },
      {
        id: 'refine-scope',
        name: 'Refine and finalize scope and deliverables',
        description: 'Define project boundaries and expected outcomes',
        automationType: 'semi-automated',
        owner: 'EA Architect',
        duration: '3 days',
        tools: ['Scope Management Tool', 'Requirements Tracker']
      },
      {
        id: 'customize-templates',
        name: 'Customize templates and questionnaires',
        description: 'Adapt standard templates to organization needs',
        automationType: 'semi-automated',
        owner: 'EA Analyst',
        duration: '2 days',
        tools: ['Template Generator', 'Survey Builder']
      },
      {
        id: 'baseline-documentation',
        name: 'Identify and baseline documentation',
        description: 'Collect existing documentation on processes, apps, and tech',
        automationType: 'fully-automated',
        owner: 'EA Analyst',
        duration: '3 days',
        tools: ['Document Scanner', 'Metadata Extractor']
      },
      {
        id: 'kickoff-meeting',
        name: 'Conduct kick-off meeting',
        description: 'Launch the EA review with all stakeholders',
        automationType: 'manual',
        owner: 'EA Team Lead',
        duration: '0.5 days',
        tools: ['Video Conference', 'Presentation Tool']
      }
    ],
    deliverables: [
      {
        id: 'engagement-plan',
        name: 'Detailed Engagement Plan',
        type: 'document',
        template: 'engagement-plan-template',
        autoGenerated: true
      },
      {
        id: 'questionnaires',
        name: 'Finalized questionnaires and templates',
        type: 'document',
        template: 'survey-template',
        autoGenerated: true
      }
    ],
    automationCapabilities: [
      {
        id: 'auto-stakeholder-mapping',
        name: 'Automated Stakeholder Mapping',
        type: 'analysis',
        status: 'available',
        description: 'AI-powered stakeholder identification from org chart'
      },
      {
        id: 'meeting-scheduler-bot',
        name: 'Meeting Scheduler Bot',
        type: 'workflow',
        status: 'available',
        description: 'Automated meeting coordination with calendar integration'
      },
      {
        id: 'template-generator',
        name: 'Template Generator',
        type: 'report',
        status: 'available',
        description: 'Dynamic template creation based on industry and size'
      }
    ],
    emailTemplates: [
      {
        id: 'kickoff-invitation',
        name: 'EA Review Kickoff Invitation',
        subject: 'Invitation: Enterprise Architecture Review Kickoff - {{date}}',
        body: `Dear {{stakeholder_name}},

We are pleased to invite you to participate in our Enterprise Architecture Review initiative.

**Purpose:** To assess and optimize our current IT landscape and align it with business strategy.

**Your Role:** As a key stakeholder in {{department}}, your insights are crucial for:
- Understanding current pain points
- Identifying improvement opportunities
- Defining future state requirements

**Kickoff Meeting Details:**
- Date: {{meeting_date}}
- Time: {{meeting_time}}
- Location/Link: {{meeting_location}}

**What to Expect:**
1. Overview of the EA review process
2. Timeline and milestones
3. Your involvement and time commitment
4. Q&A session

Please confirm your attendance by {{rsvp_date}}.

Best regards,
{{ea_team_lead}}
Enterprise Architecture Team`,
        recipients: ['stakeholders@company.com'],
        variables: ['stakeholder_name', 'department', 'date', 'meeting_date', 'meeting_time', 'meeting_location', 'rsvp_date', 'ea_team_lead'],
        schedule: 'T-7 days before kickoff'
      },
      {
        id: 'stakeholder-survey-invite',
        name: 'Stakeholder Analysis Survey',
        subject: 'Action Required: EA Stakeholder Analysis Survey',
        body: `Dear {{stakeholder_name}},

As part of our Enterprise Architecture Review, we need your input to better understand your role and requirements.

**Survey Link:** {{survey_link}}
**Completion Time:** ~10 minutes
**Deadline:** {{deadline}}

This survey will help us:
- Map key stakeholders and dependencies
- Understand your priorities and concerns
- Plan appropriate engagement levels

Your responses are confidential and will be used solely for planning purposes.

Thank you for your participation.

Best regards,
{{ea_team}}`,
        recipients: ['all-stakeholders@company.com'],
        variables: ['stakeholder_name', 'survey_link', 'deadline', 'ea_team'],
        schedule: 'Day 1 of Initiate phase'
      }
    ],
    surveys: [
      {
        id: 'stakeholder-analysis-survey',
        name: 'Stakeholder Analysis Survey',
        purpose: 'Identify stakeholder interests, influence, and requirements',
        targetAudience: ['Business Leaders', 'IT Managers', 'Process Owners'],
        automationLevel: 'automated',
        questions: [
          {
            id: 'q1',
            question: 'What is your primary role in the organization?',
            type: 'radio',
            required: true,
            options: ['Business Executive', 'IT Management', 'Process Owner', 'Technical Lead', 'End User Representative'],
            category: 'Role'
          },
          {
            id: 'q2',
            question: 'Which business processes do you own or influence?',
            type: 'checkbox',
            required: true,
            options: ['Sales', 'Marketing', 'Operations', 'Finance', 'HR', 'IT', 'Customer Service', 'Supply Chain'],
            category: 'Process'
          },
          {
            id: 'q3',
            question: 'What are your top 3 pain points with current IT systems?',
            type: 'text',
            required: true,
            category: 'Pain Points'
          },
          {
            id: 'q4',
            question: 'How critical is IT transformation to your business objectives?',
            type: 'scale',
            required: true,
            options: ['1', '2', '3', '4', '5'],
            category: 'Priority'
          },
          {
            id: 'q5',
            question: 'What is your preferred level of involvement in the EA review?',
            type: 'radio',
            required: true,
            options: ['Informed Only', 'Consulted', 'Active Participant', 'Decision Maker'],
            category: 'Engagement'
          }
        ]
      }
    ]
  },
  {
    id: 'gather',
    name: 'GATHER',
    description: 'Information collection and current state assessment',
    activities: [
      {
        id: 'understand-strategy',
        name: 'Understand business strategy and vision',
        description: 'Analyze business strategy documents and vision statements',
        automationType: 'semi-automated',
        owner: 'Business Analyst',
        duration: '3 days',
        tools: ['Strategy Parser', 'Vision Analyzer']
      },
      {
        id: 'conduct-workshops',
        name: 'Conduct workshops with stakeholders',
        description: 'Facilitate sessions to capture drivers and pain areas',
        automationType: 'semi-automated',
        owner: 'EA Facilitator',
        duration: '5 days',
        tools: ['Virtual Whiteboard', 'Workshop Recorder', 'Sentiment Analysis']
      },
      {
        id: 'baseline-current-state',
        name: 'Baseline current state EA',
        description: 'Document existing architecture landscape',
        automationType: 'fully-automated',
        owner: 'EA Architect',
        duration: '5 days',
        tools: ['Discovery Scanner', 'Architecture Mining Tool']
      },
      {
        id: 'map-architecture',
        name: 'Map application and technology to business',
        description: 'Create business capability to IT mapping',
        automationType: 'semi-automated',
        owner: 'EA Architect',
        duration: '4 days',
        tools: ['Capability Mapper', 'Dependency Analyzer']
      },
      {
        id: 'assess-initiatives',
        name: 'Assess existing IT initiatives',
        description: 'Review ongoing projects and improvements',
        automationType: 'semi-automated',
        owner: 'PMO Lead',
        duration: '2 days',
        tools: ['Project Portfolio Tool', 'Initiative Tracker']
      }
    ],
    deliverables: [
      {
        id: 'drivers-report',
        name: 'Business and IT drivers, needs, pains and gaps',
        type: 'report',
        template: 'drivers-analysis-template',
        autoGenerated: true
      },
      {
        id: 'current-state-assessment',
        name: 'Current State EA Assessment',
        type: 'report',
        template: 'current-state-template',
        autoGenerated: true
      }
    ],
    automationCapabilities: [
      {
        id: 'auto-discovery',
        name: 'Automated IT Discovery',
        type: 'analysis',
        status: 'available',
        description: 'Scan and document IT infrastructure automatically'
      },
      {
        id: 'workshop-ai-assistant',
        name: 'Workshop AI Assistant',
        type: 'workflow',
        status: 'available',
        description: 'AI-powered note taking and insight extraction'
      },
      {
        id: 'capability-mapper',
        name: 'Business Capability Mapper',
        type: 'analysis',
        status: 'available',
        description: 'Auto-map IT assets to business capabilities'
      }
    ],
    emailTemplates: [
      {
        id: 'workshop-invitation',
        name: 'Workshop Invitation',
        subject: 'Workshop Invitation: {{workshop_topic}} - {{date}}',
        body: `Dear {{participant_name}},

You are invited to participate in an Enterprise Architecture workshop.

**Topic:** {{workshop_topic}}
**Date:** {{workshop_date}}
**Time:** {{workshop_time}}
**Duration:** {{duration}}
**Location:** {{location}}

**Objectives:**
- Understand your business processes and requirements
- Identify current pain points and challenges
- Discuss improvement opportunities
- Map technology needs to business capabilities

**Preparation:**
Please review the attached pre-read materials and come prepared to discuss:
1. Your top 3 operational challenges
2. Critical business processes you manage
3. Key systems and applications you use

**RSVP:** Please confirm by {{rsvp_date}}

Best regards,
{{facilitator_name}}`,
        recipients: ['workshop-participants@company.com'],
        variables: ['participant_name', 'workshop_topic', 'date', 'workshop_date', 'workshop_time', 'duration', 'location', 'rsvp_date', 'facilitator_name'],
        attachments: ['workshop-agenda.pdf', 'pre-read-materials.pdf'],
        schedule: 'T-5 days before workshop'
      }
    ],
    surveys: [
      {
        id: 'current-state-survey',
        name: 'Current State Assessment Survey',
        purpose: 'Gather detailed information about existing systems and processes',
        targetAudience: ['IT Managers', 'System Owners', 'Process Owners'],
        automationLevel: 'automated',
        questions: [
          {
            id: 'cs1',
            question: 'List your critical business applications',
            type: 'text',
            required: true,
            category: 'Applications'
          },
          {
            id: 'cs2',
            question: 'Rate the performance of your current IT systems',
            type: 'matrix',
            required: true,
            options: ['Poor', 'Fair', 'Good', 'Excellent'],
            category: 'Performance'
          },
          {
            id: 'cs3',
            question: 'What are the main integration challenges?',
            type: 'text',
            required: true,
            category: 'Integration'
          },
          {
            id: 'cs4',
            question: 'Identify data quality issues',
            type: 'checkbox',
            required: false,
            options: ['Duplicates', 'Inconsistency', 'Incompleteness', 'Timeliness', 'Accuracy'],
            category: 'Data Quality'
          },
          {
            id: 'cs5',
            question: 'What percentage of processes are automated?',
            type: 'radio',
            required: true,
            options: ['0-20%', '21-40%', '41-60%', '61-80%', '81-100%'],
            category: 'Automation'
          }
        ]
      }
    ]
  },
  {
    id: 'analyze',
    name: 'ANALYZE',
    description: 'Gap analysis and target state definition',
    activities: [
      {
        id: 'evaluate-pain-areas',
        name: 'Evaluate pain areas and required capabilities',
        description: 'Analyze gaps between current and desired state',
        automationType: 'fully-automated',
        owner: 'EA Architect',
        duration: '4 days',
        tools: ['Gap Analysis Engine', 'Capability Assessment Tool']
      },
      {
        id: 'evaluate-trends',
        name: 'Evaluate Industry Trends',
        description: 'Research and analyze relevant industry trends',
        automationType: 'semi-automated',
        owner: 'EA Strategist',
        duration: '2 days',
        tools: ['Trend Analysis Platform', 'Industry Benchmark Tool']
      },
      {
        id: 'define-target-state',
        name: 'Define Target state enterprise architecture',
        description: 'Design future state architecture blueprint',
        automationType: 'semi-automated',
        owner: 'Chief Architect',
        duration: '5 days',
        tools: ['Architecture Designer', 'Blueprint Generator']
      },
      {
        id: 'gap-analysis',
        name: 'Perform gap analysis',
        description: 'Detailed analysis of application and technology gaps',
        automationType: 'fully-automated',
        owner: 'EA Analyst',
        duration: '3 days',
        tools: ['Gap Analyzer', 'Comparison Matrix Tool']
      }
    ],
    deliverables: [
      {
        id: 'target-state-architecture',
        name: 'Target State Enterprise Architecture',
        type: 'report',
        template: 'target-state-template',
        autoGenerated: true
      },
      {
        id: 'gap-analysis-findings',
        name: 'Gap analysis findings',
        type: 'report',
        template: 'gap-analysis-template',
        autoGenerated: true
      }
    ],
    automationCapabilities: [
      {
        id: 'ai-gap-analyzer',
        name: 'AI Gap Analyzer',
        type: 'analysis',
        status: 'available',
        description: 'ML-powered gap identification and prioritization'
      },
      {
        id: 'trend-predictor',
        name: 'Trend Predictor',
        type: 'analysis',
        status: 'in-development',
        description: 'Predictive analytics for technology trends'
      },
      {
        id: 'architecture-optimizer',
        name: 'Architecture Optimizer',
        type: 'analysis',
        status: 'available',
        description: 'Optimize target architecture based on constraints'
      }
    ],
    emailTemplates: [
      {
        id: 'analysis-review-request',
        name: 'Analysis Review Request',
        subject: 'Review Required: EA Analysis Findings',
        body: `Dear {{reviewer_name}},

We have completed the analysis phase of our Enterprise Architecture review and need your validation.

**Documents for Review:**
1. Target State Architecture Blueprint
2. Gap Analysis Report
3. Capability Assessment

**Key Findings:**
{{key_findings_summary}}

**Review Deadline:** {{deadline}}

**Action Required:**
- Review the attached documents
- Provide feedback via the review portal
- Attend validation session on {{validation_date}}

Your insights are crucial for finalizing our recommendations.

Best regards,
{{ea_team}}`,
        recipients: ['architecture-board@company.com'],
        variables: ['reviewer_name', 'key_findings_summary', 'deadline', 'validation_date', 'ea_team'],
        attachments: ['target-state.pdf', 'gap-analysis.pdf'],
        schedule: 'End of Analyze phase'
      }
    ],
    surveys: [
      {
        id: 'target-state-validation',
        name: 'Target State Validation Survey',
        purpose: 'Validate and refine target architecture with stakeholders',
        targetAudience: ['Business Leaders', 'IT Leaders', 'Architecture Board'],
        automationLevel: 'automated',
        questions: [
          {
            id: 'tv1',
            question: 'Does the target state align with business strategy?',
            type: 'scale',
            required: true,
            options: ['1', '2', '3', '4', '5'],
            category: 'Alignment'
          },
          {
            id: 'tv2',
            question: 'Are the identified gaps accurate and complete?',
            type: 'radio',
            required: true,
            options: ['Yes', 'Mostly', 'Partially', 'No'],
            category: 'Accuracy'
          },
          {
            id: 'tv3',
            question: 'What additional capabilities are needed?',
            type: 'text',
            required: false,
            category: 'Additions'
          },
          {
            id: 'tv4',
            question: 'Rate the feasibility of the target architecture',
            type: 'scale',
            required: true,
            options: ['1', '2', '3', '4', '5'],
            category: 'Feasibility'
          }
        ]
      }
    ]
  },
  {
    id: 'recommend',
    name: 'RECOMMEND',
    description: 'Recommendations and roadmap development',
    activities: [
      {
        id: 'consolidate-findings',
        name: 'Consolidate findings into recommendations',
        description: 'Synthesize all findings into actionable recommendations',
        automationType: 'semi-automated',
        owner: 'EA Lead',
        duration: '3 days',
        tools: ['Recommendation Engine', 'Priority Matrix Tool']
      },
      {
        id: 'prioritize-initiatives',
        name: 'Prioritize IT Initiatives',
        description: 'Rank initiatives by value and feasibility',
        automationType: 'fully-automated',
        owner: 'Portfolio Manager',
        duration: '2 days',
        tools: ['Priority Scoring Algorithm', 'Value Calculator']
      },
      {
        id: 'sequence-roadmap',
        name: 'Sequence and elaborate roadmaps',
        description: 'Create detailed implementation roadmaps',
        automationType: 'semi-automated',
        owner: 'EA Architect',
        duration: '4 days',
        tools: ['Roadmap Builder', 'Dependency Mapper']
      }
    ],
    deliverables: [
      {
        id: 'prioritized-recommendations',
        name: 'Prioritized recommendations',
        type: 'report',
        template: 'recommendations-template',
        autoGenerated: true
      },
      {
        id: 'implementation-roadmap',
        name: 'Implementation roadmap',
        type: 'presentation',
        template: 'roadmap-template',
        autoGenerated: true
      }
    ],
    automationCapabilities: [
      {
        id: 'recommendation-engine',
        name: 'Recommendation Engine',
        type: 'analysis',
        status: 'available',
        description: 'AI-powered recommendation generation'
      },
      {
        id: 'roadmap-optimizer',
        name: 'Roadmap Optimizer',
        type: 'workflow',
        status: 'available',
        description: 'Optimize roadmap based on dependencies and resources'
      },
      {
        id: 'roi-calculator',
        name: 'ROI Calculator',
        type: 'analysis',
        status: 'available',
        description: 'Calculate ROI for each recommendation'
      }
    ],
    emailTemplates: [
      {
        id: 'final-recommendations',
        name: 'Final Recommendations Presentation',
        subject: 'EA Review Complete: Final Recommendations and Roadmap',
        body: `Dear {{executive_name}},

We are pleased to present the final recommendations from our Enterprise Architecture Review.

**Executive Summary:**
{{executive_summary}}

**Top Recommendations:**
{{top_recommendations}}

**Investment Required:** {{total_investment}}
**Expected ROI:** {{expected_roi}}
**Timeline:** {{implementation_timeline}}

**Presentation Details:**
Date: {{presentation_date}}
Time: {{presentation_time}}
Venue: {{venue}}

**Attached Documents:**
1. Executive Summary
2. Detailed Recommendations
3. Implementation Roadmap
4. Business Case

We look forward to discussing the path forward.

Best regards,
{{ea_team_lead}}
Enterprise Architecture Team`,
        recipients: ['executives@company.com', 'architecture-board@company.com'],
        variables: ['executive_name', 'executive_summary', 'top_recommendations', 'total_investment', 'expected_roi', 'implementation_timeline', 'presentation_date', 'presentation_time', 'venue', 'ea_team_lead'],
        attachments: ['executive-summary.pdf', 'recommendations.pdf', 'roadmap.pdf', 'business-case.xlsx'],
        schedule: 'End of Recommend phase'
      }
    ],
    surveys: [
      {
        id: 'recommendation-feedback',
        name: 'Recommendation Feedback Survey',
        purpose: 'Gather feedback on recommendations and roadmap',
        targetAudience: ['Executives', 'Business Leaders', 'IT Leaders'],
        automationLevel: 'automated',
        questions: [
          {
            id: 'rf1',
            question: 'How well do recommendations address your pain points?',
            type: 'scale',
            required: true,
            options: ['1', '2', '3', '4', '5'],
            category: 'Effectiveness'
          },
          {
            id: 'rf2',
            question: 'Which recommendations should be prioritized?',
            type: 'checkbox',
            required: true,
            options: ['Cloud Migration', 'Process Automation', 'Data Integration', 'Security Enhancement', 'Customer Experience'],
            category: 'Priority'
          },
          {
            id: 'rf3',
            question: 'What is your readiness for transformation?',
            type: 'radio',
            required: true,
            options: ['Ready Now', 'Need 3-6 months', 'Need 6-12 months', 'Not Ready'],
            category: 'Readiness'
          },
          {
            id: 'rf4',
            question: 'Any concerns about the recommendations?',
            type: 'text',
            required: false,
            category: 'Concerns'
          }
        ]
      }
    ]
  }
];

// Automation Suggestions
export const automationSuggestions = [
  {
    phase: 'INITIATE',
    suggestions: [
      'Use AI-powered stakeholder mapping from organizational data',
      'Implement calendar bots for automatic meeting scheduling',
      'Deploy document scanners to baseline existing documentation',
      'Create dynamic survey generation based on organization type',
      'Set up automated reminder emails for survey completion'
    ]
  },
  {
    phase: 'GATHER',
    suggestions: [
      'Use discovery tools to automatically map IT infrastructure',
      'Implement AI note-taking in workshops for instant insights',
      'Deploy application dependency mapping tools',
      'Use process mining to understand actual workflows',
      'Implement automated data quality assessment tools'
    ]
  },
  {
    phase: 'ANALYZE',
    suggestions: [
      'Use ML algorithms for gap analysis and pattern recognition',
      'Implement automated benchmarking against industry standards',
      'Deploy optimization algorithms for target architecture',
      'Use predictive analytics for trend analysis',
      'Automate heat map generation for pain points'
    ]
  },
  {
    phase: 'RECOMMEND',
    suggestions: [
      'Use AI to generate recommendations based on gaps',
      'Implement automated prioritization using multiple criteria',
      'Deploy roadmap optimization based on dependencies',
      'Use automated ROI and business case generation',
      'Implement automated report generation with visualizations'
    ]
  }
];